export MYSQL_DATABASE=student-db
export MYSQL_ROOT_PASSWORD=1234

export MASTER_MYSQL_USER=master
export MASTER_MYSQL_PASSWORD=1234

export SLAVE1_MYSQL_USER=slave1
export SLAVE1_MYSQL_PASSWORD=1234

export SLAVE2_MYSQL_USER=slave2
export SLAVE2_MYSQL_PASSWORD=1234
